### ISSUE TITLE
Skin

### ISSUE THREAD

**Issue by deveworld** [lt-name/MurderMystery_Nukkit#12]
I put skins in plugins/MurderMystery/Skins/
But it doesn't work.
Here are the skins.

![alex](https://user-images.githubusercontent.com/48672862/86219914-d67dc080-bbbd-11ea-9af5-0b816a04ae8e.png)
![creeper](https://user-images.githubusercontent.com/48672862/86219915-d7aeed80-bbbd-11ea-8b0d-e310cae66952.png)
![drowned](https://user-images.githubusercontent.com/48672862/86219918-d8478400-bbbd-11ea-9134-c8e675868c88.png)
![husk](https://user-images.githubusercontent.com/48672862/86219920-d8478400-bbbd-11ea-825f-f920a4d410cf.png)
![irongolem](https://user-images.githubusercontent.com/48672862/86219923-d8e01a80-bbbd-11ea-9168-2d4e5347d7cc.png)
![sheep](https://user-images.githubusercontent.com/48672862/86219924-d978b100-bbbd-11ea-81ff-b4f75ad0441c.png)
![skin](https://user-images.githubusercontent.com/48672862/86219925-d978b100-bbbd-11ea-8162-9c947e38a723.png)
![villager](https://user-images.githubusercontent.com/48672862/86219927-da114780-bbbd-11ea-9dfa-24934d94af90.png)
![vindicator](https://user-images.githubusercontent.com/48672862/86219928-da114780-bbbd-11ea-95ee-b10e72e83635.png)
![witch](https://user-images.githubusercontent.com/48672862/86219929-daa9de00-bbbd-11ea-9e7e-57dcdd4b2438.png)
![zombie](https://user-images.githubusercontent.com/48672862/86219933-daa9de00-bbbd-11ea-8512-63a602bb79fe.png)
![zombiepigman](https://user-images.githubusercontent.com/48672862/86219934-db427480-bbbd-11ea-937f-c9d7bd83574f.png)

**Comment by lt-name** [comment]
MurderMystery/Skins/SkinName/skin.png
This is the path where the skin is stored
SkinName is the name of the skin

**Comment by deveworld** [comment]
Oh.. ok!
I am going to test it

**Comment by deveworld** [comment]
It works!
Thx!!
