### ISSUE TITLE
language code typo

### ISSUE THREAD

**Issue by deveworld** [lt-name/MurderMystery_Nukkit#13]
MurderMystery_Nukkit/src/main/java/cn/lanink/murdermystery/utils/Language.java
212 line

Change
this.adminLevelNoRoom = config.getString("adminStartNoRoom", this.adminLevelNoRoom);
to
this.adminLevelNoRoom = config.getString("adminLevelNoRoom", this.adminLevelNoRoom);

Thx.

**Comment by deveworld** [comment]
:D

**Comment by deveworld** [comment]
I like this project very much.
So I watched all codes.

**Comment by lt-name** [comment]
My English is very poor, so there may be a lot of grammatical errors, if you want, can you check it for me?

**Comment by lt-name** [comment]
212 line has been corrected
