### ISSUE TITLE
This phrase was displayed

### ISSUE THREAD

**Issue by JuChanMin** [lt-name/MurderMystery_Nukkit#34]
As soon as a new version was released on CloudBurst, I translated and applied plugin.

Plugin applied together : DbLib, EconomyAPI, ScoreboardAPI, KotlinLib

> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cn.lanink.murdermystery.utils.MetricsLite (file:/C:/Users/MyName/Desktop/plugins%20test/plugins/MurderMystery-1.0.8-SNAPSHOT.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of cn.lanink.murdermystery.utils.MetricsLite
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

I used PowerNukkit 1.4.0.0-SNAPSHOT (https://github.com/PowerNukkit/PowerNukkit/actions/runs/253486089)

I was building in Creative mode, this message is displayed in console.

**Comment by lt-name** [comment]
Are you using java1.8?

**Comment by JuChanMin** [comment]
> Are you using java1.8?

:o That's right, I'm using Java 1.8.x.
Is that the phrase that appears due to compatibility with Java?
Can I ignore it and use it?

**Comment by lt-name** [comment]
MetricsLite is the usage statistics of bstats.org and does not affect the main functions

**Comment by JuChanMin** [comment]
> MetricsLite is the usage statistics of bstats.org and does not affect the main functions

Thanks for always answering :)
