### ISSUE TITLE
German 

### ISSUE THREAD

**Issue by zombihunterbonn** [lt-name/MurderMystery_Nukkit#36]
Can you put german yml pls 
[Murdermysterydeutsch_201103_151301.txt](https://github.com/lt-name/MurderMystery_Nukkit/files/5481776/Murdermysterydeutsch_201103_151301.txt)

**Comment by lt-name** [comment]
I will go home a few days later, if I have time, I will add it.

Of course you can send pr directly so I can merge pr directly

(Google Translate)

**Comment by zombihunterbonn** [comment]
Okay

lt-name <notifications@github.com> schrieb am Do., 5. Nov. 2020, 11:14:
