### ISSUE TITLE
not loaded plugin

### ISSUE THREAD

**Issue by mercadanteus** [lt-name/MurderMystery_Nukkit#44]
Last update cannot be loaded, tried the previous version, but now fails too, I suppossed config files where changed.

https://pastebin.com/vMfHLqYJ

the full log: https://pastebin.com/K1KV6zbQ

**Comment by mercadanteus** [comment]
Last update cannot be loaded, tried the previous version, but now fails too, I suppossed config files where changed.

https://pastebin.com/vMfHLqYJ

the full log:  https://pastebin.com/K1KV6zbQ

**Comment by lt-name** [comment]
You can try to delete the old language files

**Comment by lt-name** [comment]
If you still have questions, you can join discord
https://discord.gg/pJjQDQC
