### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by JJBirdgender** [lt-name/MurderMystery_Nukkit#5]
Where can I download .jar that isn't mcbbs.net? Could you attach or something? Also the English translation looks good thanks! 👍

**Comment by lt-name** [comment]
https://github.com/lt-name/MurderMystery_Nukkit/actions

**Comment by JJBirdgender** [comment]
Thanks, are there any required plugins for this to work?

**Comment by lt-name** [comment]
yes,Need this:
https://github.com/lt-name/MurderMystery_Nukkit/blob/master/lib/Tips_v1.6.8.jar

**Comment by JJBirdgender** [comment]
Can I have the link for the Shop addon. Also love this plugin it's really good! Is there an English version for the Tips plugin?
