### ISSUE TITLE
Few questions including translation

### ISSUE THREAD

**Issue by VadimB131** [lt-name/MurderMystery_Nukkit#8]
Hello!

I've got some questions:

While testing we found out that a killer has some effects and players see their animation. Is it bug or should be like that? Maybe we miss the idea?

You can take nothing for gold ingots. You earn them, but how can you buy items?

I can make translation in russian for this plugin, do you think we can contact at Discord or other? If you send me the text file, I'll do that.

**Comment by lt-name** [comment]
Players can see the killer holding an iron sword

10 gold ingots are automatically replaced with a bow and an arrow
You can also use uishop to buy interesting props

Discord: lt_name#0365

**Comment by lt-name** [comment]
https://discord.gg/pJjQDQC
This is a temporary discord server invitation link. If there are enough people, it may create a formal
