### ISSUE TITLE
how do i use this plugin? How do I make a jar in a zip?

### ISSUE THREAD

**Issue by hardsiamang655** [lt-name/MurderMystery_Nukkit#8]
how do i use this plugin? How do I make a jar in a zip?

**Comment by lt-name** [comment]
Detailed introduction of this plugin:
https://www.mcbbs.net/thread-1014768-1-1.html
It is a pity that it does not support English, if you are interested, you can make English language files for him
(Google Translate)

**Comment by lt-name** [comment]
Or download via github actions
https://github.com/lt-name/MurderMystery_Nukkit/actions
