### ISSUE TITLE
MurderMystery_Nukkit 

### ISSUE THREAD

**Issue by unknowghostlife** [lt-name/MurderMystery_Nukkit#9]
[FATAL] Could not load plugin "MurderMystery": Unknown dependency
[FATAL] Could not load plugin "MurderMystery": Unknown dependency
[FATAL] Could not load plugin "MurderMystery": Circular dependency detected
idk why it say this

**Comment by lt-name** [comment]
Please install dependency:
https://github.com/lt-name/MurderMystery_Nukkit/blob/master/lib/Tips_v1.6.8-English.jar
